-hosts: aws_hosts
 become:yes

 tasks:
   -name: Install apache
    apt: name=httpd update_cache=yes state=latest
    notify:
      - restart apache2
handlers:
   -name: restart apache2
    service: name=apache2 state=started
